
Title = "Ai-detector Configuration"

# Number of samples to use from the combined dataset
# if 0, all samples will be used
num_samples = 2000

# Random state for shuffling and splitting
random_state = 42

# Test size for train-test split
test_size = 0.2

[features.nb_classifier]
enabled = true
allow_voting = true

[features.nb_classifier.params]
alpha = 1.0

[features.nb_no_stopwords]
enabled = true
allow_voting = true

[features.nb_no_stopwords.params]
alpha = 1.0

[features.random_choice]
enabled = true
allow_voting = false

[features.bert_classifier]
enabled = true
allow_voting = true

[features.bert_classifier.params]
model_name = "google-bert/bert-base-uncased"
max_length = 128
epochs = 1
lr = 0.005
