
Title = "Combined Dataset Maker"
# This is the configuration file for creating a mixed source dataset from 6 different sources:

# Total number of samples to include in the combined dataset
# if set to MAX, it uses all available samples from enabled sources
total_samples = 5000

# if true, saves the combined dataset in Apache Arrow format for efficiency, otherwise saves as csv
use_arrow = false

# if true, uses a random seed for sampling and shuffling, otherwise uses fixed seed 0
random = false

# if relaive_portion is not set, it defaults to equal distribution among enabled sources (16.67% each for 6 sources)
# set relative portion to "0.2" for 20% of the total samples from that source
# if using relative portion, ensure the sum of all relative portions equals 1.0


[ah_aitd]

enabled = true
relative_portion = 0

[ai_text_detection_pile]

enabled = true
relative_portion = 0

[daigt_v2]

enabled = true
relative_portion = 0

[hc3]

sources_to_include = [
    'reddit_eli5',
    'open_qa',
    'wiki_csai',
    'finance',
    'medicine',
]
enabled = true
relative_portion = 0

[llm_detect_competition]

enabled = true
relative_portion = 0

[sunilthite]

enabled = true
relative_portion = 0
